# Generated by Django 5.2.5 on 2026-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0002_appointment_patient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('healer', 'appointment_date', 'preferred_time'), name='unique_confirmed_healer_slot'),
        ),
    ]
